### PR TITLE
Define file structure and rectified error in Snake Game

### PR DESCRIPTION
**Pull request by pradhyumanarora**
I have

### CODE REVIEW

**Comment by Gaurang2908** [comment]
Please remove blank files and commit again

**Comment by pradhyumanarora** [comment]
I couldn't find any blank file. It would be nice if you let me know the one you found out.

**Comment by pradhyumanarora** [comment]
Can you please let me know the reason why it has been marked spam

**Comment by pradhyumanarora** [comment]
> Please remove blank files and commit again

Please dont mark it as spam.

**Pull request closed without merging**
